name: test
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Execute lint and test
    env:
      MY_SECRET: ${{secrets.commit_secret}}
      USER_NAME: githubaction
      USER_EMAIL: githubaction@fake.com
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install modules
        run: |
          yarn
      - name: Lint
        run: |
          yarn lint
      - name: Test
        run: |
          yarn test
